#!/usr/bin/env python3
"""Build the updated setup_and_backtest.ipynb with module reload fixes
and portfolio review step."""

import json

def md(source_lines, cell_id=None):
    """Create a markdown cell."""
    cell = {
        "cell_type": "markdown",
        "metadata": {},
        "source": source_lines
    }
    if cell_id:
        cell["metadata"]["id"] = cell_id
    return cell

def code(source_lines, cell_id=None):
    """Create a code cell."""
    cell = {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": source_lines
    }
    if cell_id:
        cell["metadata"]["id"] = cell_id
    return cell

cells = []

# ===== TITLE =====
cells.append(md([
    "# Sector Rotation System -- Setup & Backtest\n",
    "\n",
    "This notebook runs on **Google Colab** (free tier). It:\n",
    "\n",
    "1. Clones the repo and installs dependencies\n",
    "2. Populates the database with 2 years of historical data\n",
    "3. Runs the full pipeline (regime -> optimizer -> screener -> NLP)\n",
    "4. Executes a walk-forward backtest and displays results\n",
    "5. Shows the current Executive Summary with dollar allocations\n",
    "6. **Reviews portfolio** -- confirm/edit before downloading\n",
    "\n",
    "**Runtime:** ~5-8 minutes on Colab free tier."
]))

# ===== SECTION 1: Clone & Install =====
cells.append(md([
    "## 1. Clone Repo & Install Dependencies"
]))

cells.append(code([
    "# --- Clone private repo using Colab Secrets ---\n",
    "# Store your GitHub PAT in Colab Secrets (key icon in sidebar) as GITHUB_TOKEN.\n",
    "# The token needs 'repo' scope for private repository access.\n",
    "\n",
    "import os\n",
    "import importlib\n",
    "from pathlib import Path\n",
    "\n",
    "REPO_DIR = '/content/sector-rotation-system'\n",
    "\n",
    "if not os.path.isdir(REPO_DIR):\n",
    "    from google.colab import userdata\n",
    "    token = userdata.get('GITHUB_TOKEN')\n",
    "    !git clone https://{token}@github.com/bigbathtub101/sector-rotation-system.git {REPO_DIR}\n",
    "else:\n",
    "    print(f'Repo already cloned at {REPO_DIR}, pulling latest...')\n",
    "    !cd {REPO_DIR} && git pull\n",
    "    # -- MODULE CACHE FIX ------------------------------------------\n",
    "    # After git pull, Python's module cache still holds the OLD code.\n",
    "    # Force-reload every project module so the new code takes effect.\n",
    "    import sys\n",
    "    project_modules = [\n",
    "        'data_feeds', 'regime_detector', 'portfolio_optimizer',\n",
    "        'stock_screener', 'nlp_sentiment', 'etf_selector', 'monitor',\n",
    "    ]\n",
    "    for mod_name in project_modules:\n",
    "        if mod_name in sys.modules:\n",
    "            importlib.reload(sys.modules[mod_name])\n",
    "            print(f'  ~ Reloaded {mod_name}')\n",
    "    # --------------------------------------------------------------\n",
    "\n",
    "os.chdir(REPO_DIR)\n",
    "print(f'Working directory: {os.getcwd()}')\n",
    "\n",
    "# Install dependencies\n",
    "!pip install -q -r requirements.txt\n",
    "print('\\nSetup complete.')"
]))

# ===== SECTION 2: API Keys =====
cells.append(md([
    "## 2. Set API Keys (Optional)\n",
    "\n",
    "FRED key is optional -- the system works without it using placeholder macro data.\n",
    "Set it here if you have one."
]))

cells.append(code([
    "import os\n",
    "import re\n",
    "\n",
    "# Optional: set your FRED API key via Colab Secrets (free at https://fred.stlouisfed.org)\n",
    "# Store your key in Colab Secrets (key icon in sidebar) as FRED_API_KEY.\n",
    "try:\n",
    "    from google.colab import userdata\n",
    "    fred_key = userdata.get(\"FRED_API_KEY\")\n",
    "    if fred_key:\n",
    "        os.environ[\"FRED_API_KEY\"] = fred_key\n",
    "except Exception:\n",
    "    pass\n",
    "\n",
    "# Optional: set your SEC EDGAR email via Colab Secrets.\n",
    "try:\n",
    "    from google.colab import userdata\n",
    "    sec_email = userdata.get(\"SEC_EDGAR_EMAIL\")\n",
    "    if sec_email:\n",
    "        # Aggressively strip ALL control characters (Colab Secrets injects \\r\\n)\n",
    "        sec_email = re.sub(r\"[^\\x20-\\x7E]\", \"\", sec_email).strip()\n",
    "        if sec_email:\n",
    "            os.environ[\"SEC_EDGAR_EMAIL\"] = sec_email\n",
    "        else:\n",
    "            print(\"WARNING: SEC_EDGAR_EMAIL contained only control characters -- ignoring.\")\n",
    "except Exception:\n",
    "    pass\n",
    "\n",
    "# Verify\n",
    "fred_key = os.environ.get(\"FRED_API_KEY\", \"\")\n",
    "print(f\"FRED_API_KEY: {('set (' + fred_key[:4] + '...)') if fred_key else 'NOT SET (will use dummy macro data)'}\")\n",
    "sec_email = os.environ.get(\"SEC_EDGAR_EMAIL\", \"\")\n",
    "print(f\"SEC_EDGAR_EMAIL: {('set (' + repr(sec_email[:20]) + '...)') if sec_email else 'NOT SET (will use config.yaml default)'}\")\n",
    "if sec_email:\n",
    "    print(f\"  repr check: {repr(sec_email)}\")\n"
]))

# ===== SECTION 3: Load Config & Backfill =====
cells.append(md([
    "## 3. Load Config & Backfill Historical Data\n",
    "\n",
    "Downloads ~2 years of daily prices for all ETFs and watchlist stocks via yfinance,\n",
    "macro data from FRED (if key is set), and recent SEC filings."
]))

# Cell 3a: Load config
cells.append(code([
    "import yaml\n",
    "import sqlite3\n",
    "import inspect\n",
    "import importlib\n",
    "import pandas as pd\n",
    "from pathlib import Path\n",
    "\n",
    "# Load config\n",
    "with open('config.yaml', 'r') as f:\n",
    "    config = yaml.safe_load(f)\n",
    "\n",
    "# ----- CRITICAL: Define a single DB path used by EVERYTHING -----\n",
    "DB_PATH = Path(os.getcwd()) / 'rotation_system.db'\n",
    "\n",
    "# --- Helper: patch a module's DB_PATH everywhere it matters ---\n",
    "def patch_db_path(mod, new_path):\n",
    "    \"\"\"Overwrite a module's DB_PATH global AND fix any function\n",
    "    defaults that captured the old value at import time.\"\"\"\n",
    "    old_path = getattr(mod, 'DB_PATH', None)\n",
    "    mod.DB_PATH = new_path\n",
    "    for name, obj in inspect.getmembers(mod, inspect.isfunction):\n",
    "        if obj.__defaults__:\n",
    "            new_defaults = []\n",
    "            changed = False\n",
    "            for d in obj.__defaults__:\n",
    "                if isinstance(d, Path) and old_path and d == old_path:\n",
    "                    new_defaults.append(new_path)\n",
    "                    changed = True\n",
    "                else:\n",
    "                    new_defaults.append(d)\n",
    "            if changed:\n",
    "                obj.__defaults__ = tuple(new_defaults)\n",
    "    print(f'  {mod.__name__}.DB_PATH -> {mod.DB_PATH}')\n",
    "\n",
    "print(\"Config loaded. Portfolio total: ${:,.0f}\".format(config['portfolio']['total_value']))\n",
    "print(f\"  Taxable: ${config['portfolio']['accounts']['taxable']['value']:,.0f}\")\n",
    "print(f\"  Roth IRA: ${config['portfolio']['accounts']['roth_ira']['value']:,.0f}\")\n",
    "print(f\"  Sector ETFs: {len(config['tickers']['sector_etfs'])}\")\n",
    "wl_keys = ['watchlist_biotech', 'watchlist_ai_software', 'watchlist_defense', 'watchlist_green_materials']\n",
    "wl_count = sum(len(config['tickers'].get(k, [])) for k in wl_keys)\n",
    "print(f\"  Watchlist tickers: {wl_count}\")\n",
    "print(f\"  DB path: {DB_PATH}\")"
]))

# Cell 3b: Data backfill
cells.append(code([
    "import gc\n",
    "import sqlite3\n",
    "import datetime as dt\n",
    "\n",
    "# Force cleanup of any stale DB connections from prior cell runs\n",
    "gc.collect()\n",
    "\n",
    "# Verify DB is accessible before proceeding\n",
    "if DB_PATH.exists():\n",
    "    try:\n",
    "        _test_conn = sqlite3.connect(str(DB_PATH), timeout=30)\n",
    "        _test_conn.execute(\"PRAGMA journal_mode=WAL\")\n",
    "        _test_conn.execute(\"SELECT 1\")\n",
    "        _test_conn.close()\n",
    "        print(f\"[OK] DB file verified: {DB_PATH}\")\n",
    "    except sqlite3.OperationalError as e:\n",
    "        print(f\"[!] DB appears locked from a prior run, removing stale file: {e}\")\n",
    "        DB_PATH.unlink()\n",
    "\n",
    "import data_feeds\n",
    "importlib.reload(data_feeds)  # <- ensure latest code after git pull\n",
    "patch_db_path(data_feeds, DB_PATH)\n",
    "\n",
    "# Single shared connection -- eliminates competing connections that cause DB lock\n",
    "conn = data_feeds.init_database(DB_PATH)\n",
    "\n",
    "# Thresholds for incremental ingestion\n",
    "PRICE_FRESHNESS_DAYS = 3   # skip price download if DB is this fresh\n",
    "MIN_FILINGS_THRESHOLD = 50  # skip filings download if DB has more than this\n",
    "\n",
    "# --- Patch for NameError: name 'lookup_cik' is not defined ---\n",
    "if not hasattr(data_feeds, 'lookup_cik'):\n",
    "    import logging\n",
    "    logger = logging.getLogger(__name__)\n",
    "    def _placeholder_lookup_cik(ticker, cfg, log_warning=True):\n",
    "        if log_warning:\n",
    "            logger.warning(\"Using placeholder lookup_cik for ticker %s.\", ticker)\n",
    "        return None\n",
    "    data_feeds.lookup_cik = _placeholder_lookup_cik\n",
    "    print(\"[!]  Applied temporary patch: `data_feeds.lookup_cik` placeholder added.\")\n",
    "\n",
    "try:\n",
    "    # --- Incremental Prices ---\n",
    "    print(\"\\n[>>] Checking price data...\")\n",
    "    latest_date = None\n",
    "    try:\n",
    "        row = conn.execute(\"SELECT MAX(date) FROM prices\").fetchone()\n",
    "        if row and row[0]:\n",
    "            latest_date = row[0]\n",
    "    except Exception:\n",
    "        pass\n",
    "\n",
    "    today = dt.date.today()\n",
    "    if latest_date and (today - dt.date.fromisoformat(latest_date)).days <= PRICE_FRESHNESS_DAYS:\n",
    "        print(f\"[OK] Prices are current (latest: {latest_date}). Skipping download.\")\n",
    "        prices_summary = {\"skipped\": True}\n",
    "    else:\n",
    "        if latest_date:\n",
    "            price_start = (dt.date.fromisoformat(latest_date) + dt.timedelta(days=1)).isoformat()\n",
    "            print(f\"[>>] Fetching incremental prices from {price_start} to today...\")\n",
    "        else:\n",
    "            price_start = None\n",
    "            print(\"[>>] First run -- fetching full 2-year price history...\")\n",
    "        prices = data_feeds.fetch_prices(config, start_date=price_start)\n",
    "        prices, price_warnings = data_feeds.validate_prices(prices, config)\n",
    "        data_feeds.store_prices(conn, prices)\n",
    "        prices_summary = {\n",
    "            \"rows\": len(prices),\n",
    "            \"tickers\": int(prices[\"ticker\"].nunique()) if not prices.empty else 0,\n",
    "        }\n",
    "        if price_warnings:\n",
    "            print(f\"  [!] {len(price_warnings)} price warnings\")\n",
    "        print(f\"[OK] Prices stored: {prices_summary}\")\n",
    "\n",
    "    # --- Macro (always refresh -- fast ~5s) ---\n",
    "    print(\"\\n[>>] Fetching macro data from FRED...\")\n",
    "    macro = data_feeds.fetch_macro_data(config)\n",
    "    macro, macro_warnings = data_feeds.validate_macro(macro)\n",
    "    data_feeds.store_macro(conn, macro)\n",
    "    macro_summary = {\n",
    "        \"rows\": len(macro),\n",
    "        \"series\": int(macro[\"series_id\"].nunique()) if not macro.empty else 0,\n",
    "    }\n",
    "    print(f\"[OK] Macro stored: {macro_summary}\")\n",
    "\n",
    "    # --- SEC Filings (skip if already populated) ---\n",
    "    print(\"\\n[>>] Checking SEC filings...\")\n",
    "    filing_count = conn.execute(\"SELECT COUNT(*) FROM filings\").fetchone()[0]\n",
    "    if filing_count > MIN_FILINGS_THRESHOLD:\n",
    "        print(f\"[OK] Filings already populated ({filing_count:,} rows). Skipping download.\")\n",
    "        print(\"   To force a refresh, delete the DB file and re-run this cell.\")\n",
    "        filings_summary = {\"skipped\": True, \"existing\": filing_count}\n",
    "    else:\n",
    "        import time as _time\n",
    "        max_budget = config.get(\"sec_edgar\", {}).get(\"max_fetch_time_seconds\", 300)\n",
    "        print(f\"[>>] First run -- fetching SEC filings (budget: {max_budget}s)...\")\n",
    "        _t0 = _time.monotonic()\n",
    "        filings = data_feeds.fetch_all_filings(config)\n",
    "        _elapsed = _time.monotonic() - _t0\n",
    "        data_feeds.store_filings(conn, filings)\n",
    "        with_text = sum(1 for f in filings if f.get(\"raw_text\"))\n",
    "        metadata_only = len(filings) - with_text\n",
    "        filings_summary = {\"count\": len(filings), \"with_text\": with_text, \"metadata_only\": metadata_only}\n",
    "        print(f\"[OK] Filings stored: {len(filings):,} total in {_elapsed:.0f}s \"\n",
    "              f\"({with_text:,} with text, {metadata_only:,} metadata-only)\")\n",
    "        if len(filings) == 0:\n",
    "            print(\"  [!]  WARNING: 0 filings were fetched.\")\n",
    "\n",
    "finally:\n",
    "    conn.close()\n",
    "\n",
    "# --- Ticker Coverage Report ---\n",
    "import pandas as pd\n",
    "print(f\"\\n=== Ticker Coverage ===\")\n",
    "print(f\"  DB file exists: {DB_PATH.exists()}\")\n",
    "if DB_PATH.exists():\n",
    "    print(f\"  DB file size: {DB_PATH.stat().st_size:,} bytes\")\n",
    "    conn2 = sqlite3.connect(str(DB_PATH))\n",
    "    try:\n",
    "        for table in ['prices', 'macro_data', 'filings', 'signals']:\n",
    "            try:\n",
    "                count = pd.read_sql(f'SELECT COUNT(*) AS n FROM {table}', conn2).iloc[0]['n']\n",
    "                print(f\"  {table}: {count:,} rows\")\n",
    "            except Exception as e:\n",
    "                print(f\"  {table}: ERROR - {e}\")\n",
    "        loaded = pd.read_sql('SELECT DISTINCT ticker FROM prices', conn2)['ticker'].tolist()\n",
    "        all_expected = set()\n",
    "        for key in config['tickers']:\n",
    "            if isinstance(config['tickers'][key], list):\n",
    "                all_expected.update(config['tickers'][key])\n",
    "        missing = all_expected - set(loaded)\n",
    "        print(f\"\\n  Tickers loaded: {len(loaded)} / {len(all_expected)} expected\")\n",
    "        if missing:\n",
    "            print(f\"  Missing tickers ({len(missing)}): {sorted(missing)}\")\n",
    "            print(f\"  NOTE: OTC ADRs (BAESY, RNMBY, SAABF) and VIX indices\")\n",
    "            print(f\"  often fail on yfinance. This is expected.\")\n",
    "    finally:\n",
    "        conn2.close()\n",
    "else:\n",
    "    print(\"  ERROR: DB file was NOT created! Check ingestion logs above.\")"
]))

# ===== SECTION 4: Regime Detection =====
cells.append(md([
    "## 4. Detect Current Regime"
]))

cells.append(code([
    "import regime_detector\n",
    "importlib.reload(regime_detector)  # <- ensure latest code after git pull\n",
    "patch_db_path(regime_detector, DB_PATH)\n",
    "\n",
    "regime_result = regime_detector.run_regime_detection(config)\n",
    "\n",
    "print(\"=\" * 60)\n",
    "print(\"CURRENT REGIME\")\n",
    "print(\"=\" * 60)\n",
    "print(f\"  Regime:              {regime_result.get('dominant_regime', 'N/A')}\")\n",
    "print(f\"  Wedge Volume %:      {regime_result.get('wedge_volume_percentile', 'N/A')}\")\n",
    "print(f\"  Fast Shock Risk:     {regime_result.get('fast_shock_risk', 'N/A')}\")\n",
    "print(f\"  VIX/RV Ratio:        {regime_result.get('vix_rv_ratio', 'N/A')}\")\n",
    "print(f\"  Confirmed:           {regime_result.get('regime_confirmed', 'N/A')}\")\n",
    "print(f\"  Consecutive Days:    {regime_result.get('consecutive_days_in_regime', 'N/A')}\")"
]))

# ===== SECTION 5: CVaR Optimization =====
cells.append(md([
    "## 5. Run CVaR Optimization\n",
    "\n",
    "Runs the full CVaR optimizer with Ledoit-Wolf shrinkage and\n",
    "Longin-Solnik tail correlations. Uses the **ETF auto-selector** to pick\n",
    "best-in-class funds (e.g. FTEC over XLK, SGOV over BIL). Dollar amounts\n",
    "are split between Taxable ($100K) and Roth IRA ($44K) using tax-location rules."
]))

cells.append(code([
    "import portfolio_optimizer\n",
    "importlib.reload(portfolio_optimizer)  # <- ensure latest code after git pull\n",
    "patch_db_path(portfolio_optimizer, DB_PATH)\n",
    "\n",
    "# Also reload the ETF selector (imported by portfolio_optimizer)\n",
    "try:\n",
    "    import etf_selector\n",
    "    importlib.reload(etf_selector)\n",
    "    # Re-patch the reference inside portfolio_optimizer\n",
    "    portfolio_optimizer._get_etf_selections = etf_selector.get_selected_tickers\n",
    "    portfolio_optimizer._get_selector_asset_class_map = etf_selector.get_ticker_asset_class_map\n",
    "    portfolio_optimizer._ETF_SELECTOR_AVAILABLE = True\n",
    "    print(\"  [OK] ETF auto-selector loaded and active\")\n",
    "except ImportError:\n",
    "    print(\"  [!] ETF selector not available -- using legacy SPDR tickers\")\n",
    "\n",
    "regime = regime_result.get('dominant_regime', 'offense')\n",
    "opt_result = portfolio_optimizer.run_portfolio_optimization(cfg=config, regime=regime)\n",
    "\n",
    "total = config['portfolio']['total_value']\n",
    "taxable_val = config['portfolio']['accounts']['taxable']['value']\n",
    "roth_val = config['portfolio']['accounts']['roth_ira']['value']\n",
    "\n",
    "print(\"=\" * 80)\n",
    "print(f\"CVaR-OPTIMIZED ALLOCATION (Regime: {regime.upper()})\")\n",
    "print(f\"Portfolio: ${total:,.0f} = ${taxable_val:,.0f} Taxable + ${roth_val:,.0f} Roth IRA\")\n",
    "print(\"=\" * 80)\n",
    "\n",
    "positions = opt_result.get('positions', {})\n",
    "if positions:\n",
    "    print(f\"\\n{'Ticker':<8} {'Weight':>7} {'Total $':>10} {'Taxable $':>10} {'Roth $':>10}  Account\")\n",
    "    print(\"-\" * 75)\n",
    "    for ticker, info in sorted(positions.items(), key=lambda x: -x[1].get('pct', 0)):\n",
    "        pct = info.get('pct', 0)\n",
    "        total_d = info.get('total_dollars', pct / 100.0 * total)\n",
    "        tax_d = info.get('taxable_dollars', 0)\n",
    "        roth_d = info.get('roth_dollars', 0)\n",
    "        acct = info.get('account', 'N/A')\n",
    "        print(f\"{ticker:<8} {pct:>6.1f}% {total_d:>10,.0f} {tax_d:>10,.0f} {roth_d:>10,.0f}  {acct}\")\n",
    "\n",
    "    # Summary by account\n",
    "    tax_total = sum(info.get('taxable_dollars', 0) for info in positions.values())\n",
    "    roth_total = sum(info.get('roth_dollars', 0) for info in positions.values())\n",
    "    print(\"-\" * 75)\n",
    "    print(f\"{'TOTAL':<8} {'100%':>7} {total:>10,.0f} {tax_total:>10,.0f} {roth_total:>10,.0f}\")\n",
    "    print(f\"\\nAccount utilization: Taxable {tax_total/taxable_val:.0%} | Roth {roth_total/roth_val:.0%}\")\n",
    "\n",
    "    # -- Verify ETF auto-selector is working --\n",
    "    tickers_in_output = set(positions.keys())\n",
    "    fidelity_check = tickers_in_output & {'FTEC', 'FHLC', 'FNCL', 'FIDU', 'FDIS', 'FSTA', 'FENY', 'FMAT', 'FUTY', 'FREL', 'FCOM'}\n",
    "    franklin_check = tickers_in_output & {'FLIN', 'FLBR', 'FLJP', 'FLCH', 'FLKR', 'FLTW'}\n",
    "    sgov_check = 'SGOV' in tickers_in_output\n",
    "    spdr_check = tickers_in_output & {'XLK', 'XLV', 'XLF', 'XLI', 'XLP', 'XLU', 'XLC', 'XLY', 'XLE', 'XLB', 'XLRE'}\n",
    "    print(f\"\\n-- ETF Auto-Selector Status --\")\n",
    "    if fidelity_check or franklin_check or sgov_check:\n",
    "        print(f\"  [OK] Active -- Fidelity: {sorted(fidelity_check)}, Franklin: {sorted(franklin_check)}, Cash: {'SGOV' if sgov_check else 'N/A'}\")\n",
    "    if spdr_check:\n",
    "        print(f\"  [!]  SPDR tickers still present (not substituted): {sorted(spdr_check)}\")\n",
    "        print(f\"      If all tickers are SPDR, the selector may not have run.\")\n",
    "        print(f\"      Try: Runtime -> Restart Runtime, then re-run all cells.\")\n",
    "else:\n",
    "    print(\"No positions returned. Check optimizer logs above.\")"
]))

# ===== SECTION 6: Backtest =====
cells.append(md([
    "## 6. Walk-Forward Backtest\n",
    "\n",
    "Simulates the system over the historical period, rebalancing monthly.\n",
    "At each rebalance date, the CVaR optimizer runs with the regime detected\n",
    "at that point to produce actual per-ETF weights. Returns are computed\n",
    "using those multi-asset weights, not a simple SPY scaling factor."
]))

cells.append(code([
    "import numpy as np\n",
    "import json as json_module\n",
    "\n",
    "import portfolio_optimizer\n",
    "importlib.reload(portfolio_optimizer)  # <- ensure latest code\n",
    "patch_db_path(portfolio_optimizer, DB_PATH)\n",
    "\n",
    "total = config['portfolio']['total_value']\n",
    "\n",
    "conn = sqlite3.connect(str(DB_PATH))\n",
    "\n",
    "# --- Optimization universe (mirrors portfolio_optimizer) ---\n",
    "opt_universe = (\n",
    "    config['tickers']['sector_etfs']\n",
    "    + config['tickers']['geographic_etfs']\n",
    "    + ['BIL']\n",
    ")\n",
    "opt_universe = list(dict.fromkeys(opt_universe))\n",
    "\n",
    "# Load ETF prices for the optimization universe\n",
    "placeholders = ','.join(['?'] * len(opt_universe))\n",
    "etf_prices = pd.read_sql(\n",
    "    f\"SELECT date, ticker, adj_close FROM prices WHERE ticker IN ({placeholders}) ORDER BY date\",\n",
    "    conn, params=opt_universe, parse_dates=['date']\n",
    ")\n",
    "\n",
    "# Load SPY as benchmark\n",
    "spy = pd.read_sql(\n",
    "    \"SELECT date, adj_close FROM prices WHERE ticker='SPY' ORDER BY date\",\n",
    "    conn, parse_dates=['date']\n",
    ").set_index('date')\n",
    "spy_returns = spy['adj_close'].pct_change().dropna()\n",
    "\n",
    "# Load regime signals\n",
    "signals_df = pd.read_sql(\n",
    "    \"SELECT date, signal_data FROM signals WHERE signal_type='regime_state' ORDER BY date\",\n",
    "    conn, parse_dates=['date']\n",
    ")\n",
    "if len(signals_df) > 0:\n",
    "    signals_df['regime'] = signals_df['signal_data'].apply(\n",
    "        lambda x: json_module.loads(x).get('dominant_regime', 'offense')\n",
    "        if isinstance(x, str) else 'offense'\n",
    "    )\n",
    "    regime_series = signals_df.set_index('date')['regime']\n",
    "else:\n",
    "    regime_series = pd.Series(dtype=str, name='regime')\n",
    "\n",
    "# Build daily return matrix for ETFs\n",
    "prices_pivot = etf_prices.pivot(index='date', columns='ticker', values='adj_close')\n",
    "etf_daily_rets = prices_pivot.pct_change()\n",
    "\n",
    "# Align to common trading dates with SPY\n",
    "common_idx = spy_returns.index.intersection(etf_daily_rets.dropna(how='all').index)\n",
    "spy_returns = spy_returns.loc[common_idx]\n",
    "etf_daily_rets = etf_daily_rets.loc[common_idx]\n",
    "\n",
    "print(f\"SPY returns: {len(spy_returns)} days\")\n",
    "print(f\"ETF universe: {len(opt_universe)} tickers\")\n",
    "print(f\"Regime signals: {len(regime_series)} rows\")\n",
    "\n",
    "# --- Identify rebalance dates (first trading day of each month) ---\n",
    "monthly_first = {}\n",
    "for date in etf_daily_rets.index:\n",
    "    key = (date.year, date.month)\n",
    "    if key not in monthly_first:\n",
    "        monthly_first[key] = date\n",
    "rebalance_dates = sorted(monthly_first.values())\n",
    "print(f\"Rebalance dates: {len(rebalance_dates)} months\")\n",
    "\n",
    "# --- Run optimizer at each rebalance date ---\n",
    "print(\"Running optimizer for each rebalance date (this may take ~1 min)...\")\n",
    "weights_schedule = {}  # date -> {ticker: weight}\n",
    "for rb_date in rebalance_dates:\n",
    "    past = regime_series[regime_series.index <= rb_date]\n",
    "    regime_at = past.iloc[-1] if len(past) > 0 else 'offense'\n",
    "    try:\n",
    "        opt_res = portfolio_optimizer.run_portfolio_optimization(\n",
    "            conn=conn, cfg=config, regime=regime_at\n",
    "        )\n",
    "        positions = opt_res.get('positions', {})\n",
    "        if positions:\n",
    "            raw_w = {t: info.get('pct', 0) / 100.0 for t, info in positions.items()}\n",
    "            available = {t: w for t, w in raw_w.items() if t in etf_daily_rets.columns}\n",
    "            total_w = sum(available.values())\n",
    "            if total_w > 0:\n",
    "                weights_schedule[rb_date] = {t: w / total_w for t, w in available.items()}\n",
    "    except Exception as e:\n",
    "        print(f\"  [!] Optimizer failed for {rb_date} (regime={regime_at}): {e}\")\n",
    "\n",
    "print(f\"Optimizer ran for {len(weights_schedule)}/{len(rebalance_dates)} rebalance dates\")\n",
    "\n",
    "# --- Compute daily portfolio returns using walk-forward weights ---\n",
    "strategy_rets = []\n",
    "current_weights = {}\n",
    "for date in etf_daily_rets.index:\n",
    "    if date in weights_schedule:\n",
    "        current_weights = weights_schedule[date]\n",
    "    if current_weights:\n",
    "        row = etf_daily_rets.loc[date]\n",
    "        port_ret = sum(\n",
    "            w * (row[t] if pd.notna(row.get(t, float('nan'))) else 0.0)\n",
    "            for t, w in current_weights.items()\n",
    "        )\n",
    "    else:\n",
    "        port_ret = 0.0\n",
    "    strategy_rets.append(port_ret)\n",
    "\n",
    "strategy_returns = pd.Series(strategy_rets, index=etf_daily_rets.index, name='strategy_ret')\n",
    "\n",
    "conn.close()\n",
    "\n",
    "print(f\"Strategy returns computed: {len(strategy_returns)} days\")\n",
    "\n",
    "if len(spy_returns) > 0 and len(strategy_returns) > 0:\n",
    "    merged = spy_returns.to_frame('spy_ret').join(strategy_returns, how='inner')\n",
    "\n",
    "    if len(regime_series) > 0:\n",
    "        merged['regime'] = regime_series.reindex(merged.index, method='ffill').fillna('offense')\n",
    "    else:\n",
    "        merged['regime'] = 'offense'\n",
    "\n",
    "    merged['spy_cum'] = (1 + merged['spy_ret']).cumprod()\n",
    "    merged['strategy_cum'] = (1 + merged['strategy_ret']).cumprod()\n",
    "\n",
    "    days = len(merged)\n",
    "    ann_factor = 252 / days if days > 0 else 1\n",
    "\n",
    "    spy_total = merged['spy_cum'].iloc[-1] - 1\n",
    "    strat_total = merged['strategy_cum'].iloc[-1] - 1\n",
    "\n",
    "    spy_ann = (1 + spy_total) ** ann_factor - 1\n",
    "    strat_ann = (1 + strat_total) ** ann_factor - 1\n",
    "\n",
    "    spy_vol = merged['spy_ret'].std() * np.sqrt(252)\n",
    "    strat_vol = merged['strategy_ret'].std() * np.sqrt(252)\n",
    "\n",
    "    spy_sharpe = spy_ann / spy_vol if spy_vol > 0 else 0\n",
    "    strat_sharpe = strat_ann / strat_vol if strat_vol > 0 else 0\n",
    "\n",
    "    def max_dd(cum_series):\n",
    "        peak = cum_series.cummax()\n",
    "        dd = (cum_series - peak) / peak\n",
    "        return dd.min()\n",
    "\n",
    "    spy_mdd = max_dd(merged['spy_cum'])\n",
    "    strat_mdd = max_dd(merged['strategy_cum'])\n",
    "\n",
    "    mclean_decay = config['factor_model']['mclean_pontiff_decay']\n",
    "    alpha_raw = strat_ann - spy_ann\n",
    "    alpha_adj = alpha_raw * mclean_decay\n",
    "    mp_label = config['backtest']['mclean_pontiff_label']\n",
    "\n",
    "    dollar_gain_spy = spy_total * total\n",
    "    dollar_gain_strat = strat_total * total\n",
    "\n",
    "    print(\"=\" * 70)\n",
    "    print(\"WALK-FORWARD BACKTEST RESULTS\")\n",
    "    print(\"=\" * 70)\n",
    "    period_start = merged.index[0].strftime('%Y-%m-%d')\n",
    "    period_end = merged.index[-1].strftime('%Y-%m-%d')\n",
    "    print(f\"Period: {period_start} to {period_end} ({days} trading days)\")\n",
    "    print()\n",
    "    print(f\"{'Metric':<30} {'SPY (B&H)':>15} {'Strategy':>15}\")\n",
    "    print(\"-\" * 60)\n",
    "    print(f\"{'Total Return':<30} {spy_total:>14.1%} {strat_total:>14.1%}\")\n",
    "    print(f\"{'Annualized Return':<30} {spy_ann:>14.1%} {strat_ann:>14.1%}\")\n",
    "    print(f\"{'Annualized Volatility':<30} {spy_vol:>14.1%} {strat_vol:>14.1%}\")\n",
    "    print(f\"{'Sharpe Ratio':<30} {spy_sharpe:>14.2f} {strat_sharpe:>14.2f}\")\n",
    "    print(f\"{'Max Drawdown':<30} {spy_mdd:>14.1%} {strat_mdd:>14.1%}\")\n",
    "    print(f\"{'Dollar Gain ($144K port.)':<30} {dollar_gain_spy:>13,.0f} {dollar_gain_strat:>13,.0f}\")\n",
    "    print()\n",
    "    print(f\"Raw Alpha vs SPY:      {alpha_raw:>+.2%}\")\n",
    "    print(f\"Adjusted Alpha (x{mclean_decay}): {alpha_adj:>+.2%}\")\n",
    "    print(f\"  {mp_label}\")\n",
    "\n",
    "    print(f\"\\nRegime distribution:\")\n",
    "    regime_counts = merged['regime'].value_counts()\n",
    "    for r, ct in regime_counts.items():\n",
    "        print(f\"  {r}: {ct} days ({ct/days:.0%})\")\n",
    "else:\n",
    "    print(\"Not enough data for backtest. Run data ingestion first.\")\n",
    "    print(f\"  Debug: SPY returns = {len(spy_returns)}, strategy returns = {len(strategy_returns)}\")\n"
]))

# ===== SECTION 7: Stock Screener =====
cells.append(md([
    "## 7. Stock Screener -- Top Picks"
]))

cells.append(code([
    "import stock_screener\n",
    "importlib.reload(stock_screener)  # <- ensure latest code\n",
    "patch_db_path(stock_screener, DB_PATH)\n",
    "\n",
    "screener_result = stock_screener.run_stock_screener(cfg=config, regime=regime)\n",
    "\n",
    "print(\"=\" * 60)\n",
    "print(\"THEMATIC WATCHLIST SCORES\")\n",
    "print(\"=\" * 60)\n",
    "\n",
    "watchlists = screener_result.get('watchlist_scores', {})\n",
    "for name, data in watchlists.items():\n",
    "    if data:\n",
    "        print(f\"\\n--- {name.upper()} ---\")\n",
    "        if isinstance(data, list):\n",
    "            df = pd.DataFrame(data)\n",
    "        elif hasattr(data, 'to_string'):\n",
    "            df = data\n",
    "        else:\n",
    "            print(f\"  (unexpected format: {type(data).__name__})\")\n",
    "            continue\n",
    "        if not df.empty:\n",
    "            show_cols = [c for c in ['ticker', 'composite_score', 'momentum_score',\n",
    "                                      'quality_score', 'value_score', 'size_score',\n",
    "                                      'valuation_label', 'signal'] if c in df.columns]\n",
    "            if show_cols:\n",
    "                print(df[show_cols].head(10).to_string(index=False))\n",
    "            else:\n",
    "                print(df.head(10).to_string(index=False))\n",
    "        else:\n",
    "            print(\"  (empty)\")\n",
    "\n",
    "# Show ENTRY/EXIT signals\n",
    "signals_out = screener_result.get('signals', {})\n",
    "if signals_out:\n",
    "    print(f\"\\n{'='*60}\")\n",
    "    print(\"ENTRY / EXIT SIGNALS\")\n",
    "    print(f\"{'='*60}\")\n",
    "    for sig_type in ['entry', 'exit']:\n",
    "        sigs = signals_out.get(sig_type, [])\n",
    "        if not sigs:\n",
    "            print(f\"\\n--- {sig_type.upper()}: none ---\")\n",
    "            continue\n",
    "        print(f\"\\n--- {sig_type.upper()} ---\")\n",
    "        watchlist_sigs = [s for s in sigs if s.get('source', 'watchlist') != 'sector_screen']\n",
    "        sector_sigs = [s for s in sigs if s.get('source') == 'sector_screen']\n",
    "        if watchlist_sigs:\n",
    "            print(\"  [Watchlist]\")\n",
    "            for s in watchlist_sigs[:10]:\n",
    "                print(f\"    {s.get('ticker', '?')} ({s.get('watchlist', '')}): {s.get('reason', '')}\")\n",
    "        if sector_sigs:\n",
    "            print(\"  [Sector Screen]\")\n",
    "            for s in sector_sigs[:10]:\n",
    "                print(f\"    {s.get('ticker', '?')} ({s.get('watchlist', '')}): {s.get('reason', '')}\")\n",
    "\n",
    "# Sector Top Picks\n",
    "print(f\"\\n{'='*60}\")\n",
    "print(\"SECTOR TOP PICKS (best stocks from overweight sectors)\")\n",
    "print(f\"{'='*60}\")\n",
    "stp_data = screener_result.get('sector_top_picks', [])\n",
    "if stp_data:\n",
    "    stp_df = pd.DataFrame(stp_data)\n",
    "    show_cols = [c for c in ['ticker', 'etf', 'composite_score', 'momentum_rank',\n",
    "                               'quality_score', 'value_score', 'valuation_label'] if c in stp_df.columns]\n",
    "    print(stp_df[show_cols].to_string(index=False))\n",
    "else:\n",
    "    print(\"  (no sector top picks -- no overweight sectors identified)\")\n"
]))

# ===== SECTION 8: Full Monitor =====
cells.append(md([
    "## 8. Run Full Monitor (Executive Summary)"
]))

cells.append(code([
    "# Run the full monitor pipeline and display the executive summary.\n",
    "# --no-deliver skips Telegram/email/Sheets delivery (not configured in Colab).\n",
    "# --db explicitly passes our DB path to avoid any path mismatch.\n",
    "!python monitor.py --no-deliver --db \"{DB_PATH}\" 2>&1 | head -120"
]))

# ===== SECTION 8.5: PORTFOLIO REVIEW (NEW) =====
cells.append(md([
    "## 8.5. Review & Confirm Portfolio\n",
    "\n",
    "**Before downloading**, review the portfolio below. You can:\n",
    "- Check that the ETF auto-selector picked the right funds\n",
    "- Verify account placement (Taxable vs Roth) makes sense\n",
    "- **Edit weights** by modifying the `overrides` dict in the next cell\n",
    "\n",
    "If everything looks good, run the cell as-is (no changes needed) and proceed to Section 9."
]))

cells.append(code([
    "# =======================================================================\n",
    "#  PORTFOLIO REVIEW -- Edit overrides below to adjust before downloading\n",
    "# =======================================================================\n",
    "#\n",
    "# The optimizer produced `opt_result` in Section 5 above.\n",
    "# This cell lets you inspect and optionally modify it.\n",
    "#\n",
    "# To override a weight, add entries to the `overrides` dict below.\n",
    "# Example: overrides = {'FTEC': 12.0, 'FUTY': 0.0, 'SGOV': 5.0}\n",
    "# Weights are in PERCENT and will be re-normalized to 100%.\n",
    "# Leave empty ({}) to accept the optimizer's output as-is.\n",
    "\n",
    "overrides = {}   # <- Edit here. Example: {'FTEC': 15.0, 'FUTY': 0.0}\n",
    "\n",
    "# =======================================================================\n",
    "\n",
    "import json\n",
    "\n",
    "positions = opt_result.get('positions', {})\n",
    "total = config['portfolio']['total_value']\n",
    "taxable_val = config['portfolio']['accounts']['taxable']['value']\n",
    "roth_val = config['portfolio']['accounts']['roth_ira']['value']\n",
    "\n",
    "# Build current weights from optimizer output\n",
    "current_weights = {t: info['pct'] for t, info in positions.items()}\n",
    "\n",
    "# Apply overrides\n",
    "if overrides:\n",
    "    print(\"[>>] Applying manual overrides...\")\n",
    "    for ticker, new_pct in overrides.items():\n",
    "        old_pct = current_weights.get(ticker, 0)\n",
    "        current_weights[ticker] = new_pct\n",
    "        print(f\"  {ticker}: {old_pct:.1f}% -> {new_pct:.1f}%\")\n",
    "\n",
    "    # Remove zero-weight positions\n",
    "    current_weights = {t: w for t, w in current_weights.items() if w > 0}\n",
    "\n",
    "    # Re-normalize to 100%\n",
    "    total_pct = sum(current_weights.values())\n",
    "    if total_pct > 0 and abs(total_pct - 100.0) > 0.1:\n",
    "        scale = 100.0 / total_pct\n",
    "        current_weights = {t: round(w * scale, 2) for t, w in current_weights.items()}\n",
    "        print(f\"  Re-normalized from {total_pct:.1f}% to 100.0%\")\n",
    "\n",
    "    # Re-run dollar allocation with updated weights\n",
    "    weight_fracs = {t: w / 100.0 for t, w in current_weights.items()}\n",
    "    importlib.reload(portfolio_optimizer)\n",
    "    positions = portfolio_optimizer.allocate_dollars(weight_fracs, config)\n",
    "    opt_result['positions'] = positions\n",
    "    print(\"  [OK] Dollar allocation recalculated with overrides.\\n\")\n",
    "else:\n",
    "    print(\"No overrides -- using optimizer output as-is.\\n\")\n",
    "\n",
    "# -- Display final portfolio for review --\n",
    "print(\"=\" * 100)\n",
    "print(f\"  FINAL PORTFOLIO -- {regime.upper()} REGIME\")\n",
    "print(f\"  ${total:,.0f} = ${taxable_val:,.0f} Taxable + ${roth_val:,.0f} Roth IRA\")\n",
    "print(\"=\" * 100)\n",
    "\n",
    "# Separate ETFs and individual stocks\n",
    "etf_pos = {t: info for t, info in positions.items()\n",
    "           if info.get('reason', '').find('satellite stock') == -1}\n",
    "stock_pos = {t: info for t, info in positions.items()\n",
    "             if info.get('reason', '').find('satellite stock') != -1}\n",
    "\n",
    "# --- ETF Core positions ---\n",
    "print(f\"\\n-- ETF Core Positions --\")\n",
    "print(f\"{'#':<3} {'Ticker':<8} {'Type':<6} {'Weight':>7} {'Total $':>10} {'Taxable $':>10} {'Roth $':>10}  {'Account':<10} Reason\")\n",
    "print(\"-\" * 110)\n",
    "\n",
    "sorted_etfs = sorted(etf_pos.items(), key=lambda x: -x[1].get('pct', 0))\n",
    "tax_total = 0\n",
    "roth_total_ = 0\n",
    "for i, (ticker, info) in enumerate(sorted_etfs, 1):\n",
    "    pct = info.get('pct', 0)\n",
    "    total_d = info.get('total_dollars', 0)\n",
    "    tax_d = info.get('taxable_dollars', 0)\n",
    "    roth_d = info.get('roth_dollars', 0)\n",
    "    acct = info.get('account', 'N/A')\n",
    "    reason = info.get('reason', '')\n",
    "    tax_total += tax_d\n",
    "    roth_total_ += roth_d\n",
    "    print(f\"{i:<3} {ticker:<8} {'ETF':<6} {pct:>6.1f}% ${total_d:>9,.0f} ${tax_d:>9,.0f} ${roth_d:>9,.0f}  {acct:<10} {reason}\")\n",
    "\n",
    "# --- Individual Stock Satellite positions ---\n",
    "if stock_pos:\n",
    "    print(f\"\\n-- Roth IRA Satellite Stocks (Top 5 from Screener) --\")\n",
    "    print(f\"{'#':<3} {'Ticker':<8} {'Type':<6} {'Weight':>7} {'Total $':>10} {'Taxable $':>10} {'Roth $':>10}  {'Account':<10} Reason\")\n",
    "    print(\"-\" * 110)\n",
    "    sorted_stocks = sorted(stock_pos.items(), key=lambda x: -x[1].get('pct', 0))\n",
    "    for j, (ticker, info) in enumerate(sorted_stocks, len(sorted_etfs) + 1):\n",
    "        pct = info.get('pct', 0)\n",
    "        total_d = info.get('total_dollars', 0)\n",
    "        tax_d = info.get('taxable_dollars', 0)\n",
    "        roth_d = info.get('roth_dollars', 0)\n",
    "        acct = info.get('account', 'N/A')\n",
    "        reason = info.get('reason', '')\n",
    "        tax_total += tax_d\n",
    "        roth_total_ += roth_d\n",
    "        print(f\"{j:<3} {ticker:<8} {'STOCK':<6} {pct:>6.1f}% ${total_d:>9,.0f} ${tax_d:>9,.0f} ${roth_d:>9,.0f}  {acct:<10} {reason}\")\n",
    "\n",
    "print(\"-\" * 110)\n",
    "print(f\"{'':3} {'TOTAL':<8} {'':6} {'100.0':>6}% ${tax_total + roth_total_:>9,.0f} ${tax_total:>9,.0f} ${roth_total_:>9,.0f}\")\n",
    "print(f\"\\n  Taxable: ${tax_total:,.0f} / ${taxable_val:,.0f} ({tax_total/taxable_val:.0%})\")\n",
    "print(f\"  Roth:    ${roth_total_:,.0f} / ${roth_val:,.0f} ({roth_total_/roth_val:.0%})\")\n",
    "if stock_pos:\n",
    "    stock_total = sum(info.get('total_dollars', 0) for info in stock_pos.values())\n",
    "    stock_roth_pct = stock_total / roth_val * 100 if roth_val > 0 else 0\n",
    "    print(f\"  Satellite stocks: ${stock_total:,.0f} = {stock_roth_pct:.0f}% of Roth IRA ({len(stock_pos)} positions)\")\n",
    "\n",
    "# -- ETF selector verification --\n",
    "tickers_in_output = set(positions.keys())\n",
    "fidelity = tickers_in_output & {'FTEC','FHLC','FNCL','FIDU','FDIS','FSTA','FENY','FMAT','FUTY','FREL','FCOM'}\n",
    "franklin = tickers_in_output & {'FLIN','FLBR','FLJP','FLCH','FLKR','FLTW'}\n",
    "spdr = tickers_in_output & {'XLK','XLV','XLF','XLI','XLP','XLU','XLC','XLY','XLE','XLB','XLRE'}\n",
    "print(f\"\\n-- ETF Auto-Selector --\")\n",
    "if fidelity: print(f\"  Fidelity MSCI: {sorted(fidelity)}\")\n",
    "if franklin: print(f\"  Franklin FTSE: {sorted(franklin)}\")\n",
    "if 'SGOV' in tickers_in_output: print(f\"  Cash: SGOV [OK]\")\n",
    "if 'BIL' in tickers_in_output: print(f\"  Cash: BIL [!] (expected SGOV)\")\n",
    "if spdr: print(f\"  SPDR (not substituted): {sorted(spdr)}\")\n",
    "\n",
    "print(\"\\n\" + \"=\" * 80)\n",
    "print(\"  [OK] If this looks correct, proceed to Section 9 to download.\")\n",
    "print(\"  [>>] To change weights, edit the `overrides` dict above and re-run this cell.\")\n",
    "print(\"=\" * 80)"
]))

# ===== SECTION 9: Download =====
cells.append(md([
    "## 9. Download Database\n",
    "\n",
    "Download the populated database to your local machine for use with\n",
    "the Streamlit dashboard or further analysis."
]))

cells.append(code([
    "from google.colab import files\n",
    "\n",
    "# Save the reviewed allocation to JSON so the dashboard picks it up\n",
    "import json\n",
    "alloc_path = DB_PATH.parent / 'current_allocation.json'\n",
    "with open(alloc_path, 'w') as f:\n",
    "    json.dump(opt_result, f, indent=2, default=str)\n",
    "print(f\"Allocation saved to {alloc_path}\")\n",
    "\n",
    "# Download the populated database\n",
    "files.download(str(DB_PATH))\n",
    "print(\"Database downloaded. Place it in the repo root for the dashboard.\")"
]))

# ===== BUILD NOTEBOOK =====
notebook = {
    "nbformat": 4,
    "nbformat_minor": 0,
    "metadata": {
        "colab": {
            "provenance": [],
            "toc_visible": True
        },
        "kernelspec": {
            "name": "python3",
            "display_name": "Python 3"
        },
        "language_info": {
            "name": "python"
        }
    },
    "cells": cells
}

output_path = "/home/user/workspace/sector_rotation_system/notebooks/setup_and_backtest.ipynb"
with open(output_path, "w") as f:
    json.dump(notebook, f, indent=2)

print(f"Notebook written to {output_path}")
print(f"Total cells: {len(cells)}")
print(f"Markdown cells: {sum(1 for c in cells if c['cell_type'] == 'markdown')}")
print(f"Code cells: {sum(1 for c in cells if c['cell_type'] == 'code')}")
